export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

// MOVIES ACTIONS
export const REQUEST_MOVIES = 'REQUEST_MOVIES'
export const RECEIVE_MOVIES = 'RECEIVE_MOVIES'
export const SELECT_THEATERS = 'SELECT_THEATERS'
export const INVALIDATE_THEATERS = 'INVALIDATE_THEATERS'
